### ISSUE TITLE
Yet another DLL error: Could not open library libcurl.dll

### ISSUE THREAD

**Issue by RemySphere** [typhoeus/typhoeus#544]
Hello everyone,
As a last resort, I'm opening an issue here.

I'm building a simple script in ruby that requires Typhoeus, but it fails to run properly.

`D:/remy/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.9.14-x86-mingw32/lib/ffi/library.rb:147:in 'block in ffi_lib': Could not open library 'libcurl': ="ÞbøíæüíæÈáõ. (LoadError)`

Both `libcurl.dll` and `curl.exe` are in my Windows PATH variable, and running `curl --version` gives me the expected output:
`curl 7.50.3 (x86_64-pc-win32) libcurl/7.50.3 OpenSSL/1.1.0b zlib/1.2.8 WinIDN libssh2/1.8.0 nghttp2/1.16.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2`

I'm trying to build curl from scratch, currently installing cygwin, but I doubt it's going to change anything.
I'm running Windows 10 x64, and Ruby 1.9.3 (I didn't get to chose my work env)

Any idea on what I'm doing wrong?
Regards

**Comment by BackOrder** [comment]
You could perhaps use a different version of curl. I successfully used [curl-7.40.0-rtmp-ssh2-ssl-sspi-zlib-idn-static-bin-w32.7z](https://curl.haxx.se/gknw.net/7.40.0/dist-w32/curl-7.40.0-rtmp-ssh2-ssl-sspi-zlib-idn-static-bin-w32.7z) on Windows 10 x64, though ruby version is higher than yours.

**Comment by mahmodjay** [comment]
@BackOrder the same url for win7 ?

**Comment by BackOrder** [comment]
@mahmodjay yes, it should be working on Win7 x64 as well.

**Comment by TT--** [comment]
any of libcurl.dll from packages at https://curl.haxx.se/gknw.net/7.40.0/ seems to work

**Comment by RemySphere** [comment]
Wow this was ages ago haha
I can confirm it works with earlier versions. Thanks for the followup

**Comment by AxelTerizaki** [comment]
Does anyone have a 7.40 version somewhere?

I still get the missing DLL error with the most recent versions (7.61) and can't seem to get an earlier version than that (can't compile from sources from where I am using this)

**Comment by AxelTerizaki** [comment]
nvm, managed to find one on a DLL download site. 7.40 seems to work fine, but newer libcurl versions do not. 

This is a little problematic as curl's website doesn't allow you to download previous releases of this dll.

**Comment by dapi** [comment]
Here is very nice solution for appveyor (download libcurl and put dll and lib into PATH) - https://github.com/ldc-developers/ldc/blob/master/appveyor.yml#L35-L50

**Comment by AlexandreMarchand1997** [comment]
@AxelTerizaki I have te same problem. On which site did you download the dll.
Thanks !!!
